// <auto-generated />
namespace JobScrapping.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class jobscrapping : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(jobscrapping));
        
        string IMigrationMetadata.Id
        {
            get { return "201403271626362_jobscrapping"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
